## GitHub Actions Workflow - CICD

name: CI/CD Workflow
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Matches Semver-like tags such as 1.0.0

jobs:
  build:
    uses: ./.github/workflows/template_build.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  # Job for deploying the application to dev