## GitHub Actions Workflow - CICD

name: CI/CD Workflow
on:
  workflow_dispatch:
  push:
    branches:
        - main
        - feature/**

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
