# This workflow is used for building and pushing the Docker image to Docker Hub.

name: Deployment Workflow template

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true

# Define environment variables used in the workflow.
env:
    DOCKERHUB_USERNAME: josefloressv
    REPO_NAME: webapp-color

# Define the jobs in the workflow.
jobs: 
    # Job for building and pushing the Docker image.
    build_and_push:
      name: Build and Push to Docker Hub
      runs-on: ubuntu-24.04
      outputs:
        image_tag: ${{ steps.tag.outputs.image_tag }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 # https://github.com/actions/checkout

        - name: Setup Docker buildx
          uses: docker/setup-buildx-action@v3 # https://github.com/docker/setup-buildx-action

        - name: Login to Docker Hub
          uses: docker/login-action@v3 # https://github.com/docker/login-action
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}           

        - name: Create Docker Image Tag
          id: tag
          run: |
            if [ -n "${GITHUB_REF_TYPE}" ] && [ "${GITHUB_REF_TYPE}" == "tag" ]; then
              echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            else
              echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
            fi

        # Push only on the main branch.
        - name: Build and push
          id: build
          # if: github.ref == 'refs/heads/main'
          uses: docker/build-push-action@v6 # https://github.com/docker/build-push-action
          with:
            context: .
            file: ./Dockerfile
            no-cache: true
            push: true
            attests: type=sbom
            platforms: linux/amd64,linux/arm64
            tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.image_tag }}
